### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by bartkamphorst** [cbitstech/Purple-Robot#282]
Hi there,

I noticed that the last commit of this project is from about 7 years ago. Is this app still maintained?

Thanks!

**Comment by bartkamphorst** [comment]
Ping @audaciouscode . Can you tell me what the status of this project is? Thanks!

**Comment by audaciouscode** [comment]
This app is currently archived and no longer being currently developed. If you're looking for a replacement, e-mail me at chris@audacious-software.com and I'll be happy to fill you in on developments since this project.
